<?php

/**
 * Listrak Remarketing Magento Extension Ver. 2.0.0
 *
 * PHP version 5
 *
 * @category  Listrak
 * @package   Listrak_Remarketing
 * @author    Listrak Magento Team <magento@listrak.com>
 * @copyright 2015 Listrak Inc
 * @license   http://s1.listrakbi.com/licenses/magento.txt License For Customer Use of Listrak Software
 * @link      http://www.listrak.com
 */

/**
 * Fingerpring tracking template
 *
 * @see \Listrak\Remarketing\Block\Conversion\Fingerprint
 */
?>
<img src="<?=$block->escapeUrl($block->getFingerprintImageUrl()) ?>" width="1" height="1" style="position: absolute" />