<?php
/**
 * Copyright © 2015 Listrak. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * OneScript template
 *
 * @see \Listrak\Remarketing\Block\Onescript
 * @see \Listrak\Remarketing\Block\Subscriber
 */
?>
<script type="text/javascript">
require(['jquery'], function(jQuery) {
    (function (d, s, id, url) {
        var js, ljs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id; js.src = url; js.type = "text/javascript";
        ljs.parentNode.insertBefore(js, ljs);
    })(document, 'script', 'ltkSDK', '<?=/* @noEscape */$block->getScriptSrc()?>');
});
</script>