<?php

/**
 * Listrak Remarketing Magento Extension Ver. 2.0.0
 *
 * PHP version 5
 *
 * @category  Listrak
 * @package   Listrak_Remarketing
 * @author    Listrak Magento Team <magento@listrak.com>
 * @copyright 2015 Listrak Inc
 * @license   http://s1.listrakbi.com/licenses/magento.txt License For Customer Use of Listrak Software
 * @link      http://www.listrak.com
 */

/**
 * Wrapper for OneScript code
 *
 * @see \Listrak\Remarketing\Block\Base
 */

$script = trim($block->getScriptBlock());
if (!$block->getWithoutUtils()) {
    $script = "require(['listrak_utils'], function(utils) { {$script} });";
}
?>
<script type="text/javascript">
(function(d) { if (document.addEventListener) document.addEventListener('ltkAsyncListener', d);
    else {e = document.documentElement; e.ltkAsyncProperty = 0; e.attachEvent('onpropertychange', function (e) {
    if (e.propertyName == 'ltkAsyncProperty' && typeof _ltk !== 'undefined'){d();}});}})
    (function() { <?=/* @noEscape */$script?> });
</script>